var map_config = {
	'default':{
		'bordercolor':'#9CA8B6', //inter-state borders
		'lakescolor':'#66CCFF', //lakes color
		'shadowcolor':'#000000', //shadow color below the map
		'shadowOpacity':'50', //shadow opacity, value, 0-100
		'namescolor':'#333', //color of the abbreviations 
		'namesShadowColor':'#666666', //tooltip shadow color
	},
	'map_1':{
		'namesId':'AL',//name's ID (Don't change it)
		'name': 'ALABAMA',  //state name
		'url':'../apartment/university.html?areaid='+vi_ALABAMA, //Goto URL
		'target':'_parent', //open link in new window:, open in current window:_self
		'upcolor':co_up_ALABAMA, //state's color when page loads
		'overcolor':co_over_ALABAMA, //state's color when mouse hover
		'downcolor':co_down_ALABAMA,//state's color when mouse clicking
		'enable':if_ALABAMA,//true/false to enable/disable this state
	},
	'map_2':{
		'namesId':'AK',
		'name': 'ALASKA',
		'url':'../apartment/university.html?areaid='+vi_ALASKA,
		'target':'_parent',
		'upcolor':co_up_ALASKA,
		'overcolor':co_over_ALASKA,
		'downcolor':co_down_ALASKA,
		'enable':if_ALASKA,
	},
	'map_3':{
		'namesId':'AZ',
		'name': 'ARIZONA',
		'url':'../apartment/university.html?areaid='+vi_ARIZONA,
		'target':'_parent',
		'upcolor':co_up_ARIZONA,
		'overcolor':co_over_ARIZONA,
		'downcolor':co_down_ARIZONA,
		'enable':if_ARIZONA,
	},
	'map_4':{
		'namesId':'AR',
		'name': 'ARKANSAS',
		'url':'../apartment/university.html?areaid='+vi_ARKANSAS,
		'target':'_parent',
		'upcolor':co_up_ARKANSAS,
		'overcolor':co_over_ARKANSAS,
		'downcolor':co_down_ARKANSAS,
		'enable':if_ARKANSAS,
	},
	'map_5':{
		'namesId':'CA',
		'name': 'CALIFORNIA',
		'url':'../apartment/university.html?areaid='+vi_CALIFORNIA,
		'target':'_parent',
		'upcolor':co_up_CALIFORNIA,
		'overcolor':co_over_CALIFORNIA,
		'downcolor':co_down_CALIFORNIA,
		'enable':if_CALIFORNIA,
	},	
	'map_6':{
		'namesId':'CO',
		'name': 'COLORADO',
		'url':'../apartment/university.html?areaid='+vi_COLORADO,
		'target':'_parent',
		'upcolor':co_up_COLORADO,
		'overcolor':co_over_COLORADO,
		'downcolor':co_down_COLORADO,
		'enable':if_COLORADO,
	},
	'map_7':{
		'namesId':'CT',
		'name': 'CONNECTICUT',
		'url':'../apartment/university.html?areaid='+vi_CONNECTICUT,
		'target':'_parent',
		'upcolor':co_up_CONNECTICUT,
		'overcolor':co_over_CONNECTICUT,
		'downcolor':co_down_CONNECTICUT,
		'enable':if_CONNECTICUT,
	},
	'map_8':{
		'namesId':'DE',
		'name': 'DELAWARE',
		'url':'../apartment/university.html?areaid='+vi_DELAWARE,
		'target':'_parent',
		'upcolor':co_up_DELAWARE,
		'overcolor':co_over_DELAWARE,
		'downcolor':co_down_DELAWARE,
		'enable':if_DELAWARE,
	},	
	'map_9':{
		'namesId':'FL',
		'name': 'FLORIDA',
		'url':'../apartment/university.html?areaid='+vi_FLORIDA,
		'target':'_parent',
		'upcolor':co_up_FLORIDA,
		'overcolor':co_over_FLORIDA,
		'downcolor':co_down_FLORIDA,
		'enable':if_FLORIDA,
	},
	'map_10':{
		'namesId':'GA',
		'name': 'GEORGIA',
		'url':'../apartment/university.html?areaid='+vi_GEORGIA,
		'target':'_parent',
		'upcolor':co_up_GEORGIA,
		'overcolor':co_over_GEORGIA,
		'downcolor':co_down_GEORGIA,
		'enable':if_GEORGIA,
	},
	'map_11':{
		'namesId':'HI',
		'name': 'HAWAII',
		'url':'../apartment/university.html?areaid='+vi_HAWAII,
		'target':'_parent',
		'upcolor':co_up_HAWAII,
		'overcolor':co_over_HAWAII,
		'downcolor':co_down_HAWAII,
		'enable':if_HAWAII,
	},	
	'map_12':{
		'namesId':'ID',
		'name': 'IDAHO',
		'url':'../apartment/university.html?areaid='+vi_IDAHO,
		'target':'_parent',
		'upcolor':co_up_IDAHO,
		'overcolor':co_over_IDAHO,
		'downcolor':co_down_IDAHO,
		'enable':if_IDAHO,
	},
	'map_13':{
		'namesId':'IL',
		'name': 'ILLINOIS',
		'url':'../apartment/university.html?areaid='+vi_ILLINOIS,
		'target':'_parent',
		'upcolor':co_up_ILLINOIS,
		'overcolor':co_over_ILLINOIS,
		'downcolor':co_down_ILLINOIS,
		'enable':if_ILLINOIS,
	},
	'map_14':{
		'namesId':'IN',
		'name': 'INDIANA',
		'url':'../apartment/university.html?areaid='+vi_INDIANA,
		'target':'_parent',
		'upcolor':co_up_INDIANA,
		'overcolor':co_over_INDIANA,
		'downcolor':co_down_INDIANA,
		'enable':if_INDIANA,
	},
	'map_15':{
		'namesId':'IA',
		'name': 'IOWA',
		'url':'../apartment/university.html?areaid='+vi_IOWA,
		'target':'_parent',
		'upcolor':co_up_IOWA,
		'overcolor':co_over_IOWA,
		'downcolor':co_down_IOWA,
		'enable':if_IOWA,
	},	
	'map_16':{
		'namesId':'KS',
		'name': 'KANSAS',
		'url':'../apartment/university.html?areaid='+vi_KANSAS,
		'target':'_parent',
		'upcolor':co_up_KANSAS,
		'overcolor':co_over_KANSAS,
		'downcolor':co_down_KANSAS,
		'enable':if_KANSAS,
	},
	'map_17':{
		'namesId':'KY',
		'name': 'KENTUCKY',
		'url':'../apartment/university.html?areaid='+vi_KENTUCKY,
		'target':'_parent',
		'upcolor':co_up_KENTUCKY,
		'overcolor':co_over_KENTUCKY,
		'downcolor':co_down_KENTUCKY,
		'enable':if_KENTUCKY,
	},
	'map_18':{
		'namesId':'LA',
		'name': 'LOUISIANA',
		'url':'../apartment/university.html?areaid='+vi_LOUISIANA,
		'target':'_parent',
		'upcolor':co_up_LOUISIANA,
		'overcolor':co_over_LOUISIANA,
		'downcolor':co_down_LOUISIANA,
		'enable':if_LOUISIANA,
	},	
	'map_19':{
		'namesId':'ME',
		'name': 'MAINE',
		'url':'../apartment/university.html?areaid='+vi_MAINE,
		'target':'_parent',
		'upcolor':co_up_MAINE,
		'overcolor':co_over_MAINE,
		'downcolor':co_down_MAINE,
		'enable':if_MAINE,
	},
	'map_20':{
		'namesId':'MD',
		'name': 'MARYLAND',
		'url':'../apartment/university.html?areaid='+vi_MARYLAND,
		'target':'_parent',
		'upcolor':co_up_MARYLAND,
		'overcolor':co_over_MARYLAND,
		'downcolor':co_down_MARYLAND,
		'enable':if_MARYLAND,
	},
	'map_21':{
		'namesId':'MA',
		'name': 'MASSACHUSETTS',
		'url':'../apartment/university.html?areaid='+vi_MASSACHUSETTS,
		'target':'_parent',
		'upcolor':co_up_MASSACHUSETTS,
		'overcolor':co_over_MASSACHUSETTS,
		'downcolor':co_down_MASSACHUSETTS,
		'enable':if_MASSACHUSETTS,
	},	
	'map_22':{
		'namesId':'MI',
		'name': 'MICHIGAN',
		'url':'../apartment/university.html?areaid='+vi_MICHIGAN,
		'target':'_parent',
		'upcolor':co_up_MICHIGAN,
		'overcolor':co_over_MICHIGAN,
		'downcolor':co_down_MICHIGAN,
		'enable':if_MICHIGAN,
	},
	'map_23':{
		'namesId':'MN',
		'name': 'MINNESOTA',
		'url':'../apartment/university.html?areaid='+vi_MINNESOTA,
		'target':'_parent',
		'upcolor':co_up_MINNESOTA,
		'overcolor':co_over_MINNESOTA,
		'downcolor':co_down_MINNESOTA,
		'enable':if_MINNESOTA,
	},
	'map_24':{
		'namesId':'MS',
		'name': 'MISSISSIPPI',
		'url':'../apartment/university.html?areaid='+vi_MISSISSIPPI,
		'target':'_parent',
		'upcolor':co_up_MISSISSIPPI,
		'overcolor':co_over_MISSISSIPPI,
		'downcolor':co_down_MISSISSIPPI,
		'enable':if_MISSISSIPPI,
	},
	'map_25':{
		'namesId':'MO',
		'name': 'MISSOURI',
		'url':'../apartment/university.html?areaid='+vi_MISSOURI,
		'target':'_parent',
		'upcolor':co_up_MISSOURI,
		'overcolor':co_over_MISSOURI,
		'downcolor':co_down_MISSOURI,
		'enable':if_MISSOURI,
	},	
	'map_26':{
		'namesId':'MT',
		'name': 'MONTANA',
		'url':'../apartment/university.html?areaid='+vi_MONTANA,
		'target':'_parent',
		'upcolor':co_up_MONTANA,
		'overcolor':co_over_MONTANA,
		'downcolor':co_down_MONTANA,
		'enable':if_MONTANA,
	},
	'map_27':{
		'namesId':'NE',
		'name': 'NEBRASKA',
		'url':'../apartment/university.html?areaid='+vi_NEBRASKA,
		'target':'_parent',
		'upcolor':co_up_NEBRASKA,
		'overcolor':co_over_NEBRASKA,
		'downcolor':co_down_NEBRASKA,
		'enable':if_NEBRASKA,
	},
	'map_28':{
		'namesId':'NV',
		'name': 'NEVADA',
		'url':'../apartment/university.html?areaid='+vi_NEVADA,
		'target':'_parent',
		'upcolor':co_up_NEVADA,
		'overcolor':co_over_NEVADA,
		'downcolor':co_down_NEVADA,
		'enable':if_NEVADA,
	},	
	'map_29':{
		'namesId':'NH',
		'name': 'NEW HAMPSHIRE',
		'url':'../apartment/university.html?areaid='+vi_NEW_HAMPSHIRE,
		'target':'_parent',
		'upcolor':co_up_NEW_HAMPSHIRE,
		'overcolor':co_over_NEW_HAMPSHIRE,
		'downcolor':co_down_NEW_HAMPSHIRE,
		'enable':if_NEW_HAMPSHIRE,
	},
	'map_30':{
		'namesId':'NJ',
		'name': 'NEW JERSEY',
		'url':'../apartment/university.html?areaid='+vi_NEW_JERSEY,
		'target':'_parent',
		'upcolor':co_up_NEW_JERSEY,
		'overcolor':co_over_NEW_JERSEY,
		'downcolor':co_down_NEW_JERSEY,
		'enable':if_NEW_JERSEY,
	},
	'map_31':{
		'namesId':'NM',
		'name': 'NEW MEXICO',
		'url':'../apartment/university.html?areaid='+vi_NEW_MEXICO,
		'target':'_parent',
		'upcolor':co_up_NEW_MEXICO,
		'overcolor':co_over_NEW_MEXICO,
		'downcolor':co_down_NEW_MEXICO,
		'enable':if_NEW_MEXICO,
	},	
	'map_32':{
		'namesId':'NY',
		'name': 'NEW YORK',
		'url':'../apartment/university.html?areaid='+vi_NEW_YORK,
		'target':'_parent',
		'upcolor':co_up_NEW_YORK,
		'overcolor':co_over_NEW_YORK,
		'downcolor':co_down_NEW_YORK,
		'enable':if_NEW_YORK,
	},
	'map_33':{
		'namesId':'NC',
		'name': 'NORTH CAROLINA',
		'url':'../apartment/university.html?areaid='+vi_NORTH_CAROLINA,
		'target':'_parent',
		'upcolor':co_up_NORTH_CAROLINA,
		'overcolor':co_over_NORTH_CAROLINA,
		'downcolor':co_down_NORTH_CAROLINA,
		'enable':if_NORTH_CAROLINA,
	},
	'map_34':{
		'namesId':'ND',
		'name': 'NORTH DAKOTA',
		'url':'../apartment/university.html?areaid='+vi_NORTH_DAKOTA,
		'target':'_parent',
		'upcolor':co_up_NORTH_DAKOTA,
		'overcolor':co_over_NORTH_DAKOTA,
		'downcolor':co_down_NORTH_DAKOTA,
		'enable':if_NORTH_DAKOTA,
	},
	'map_35':{
		'namesId':'OH',
		'name': 'OHIO',
		'url':'../apartment/university.html?areaid='+vi_OHIO,
		'target':'_parent',
		'upcolor':co_up_OHIO,
		'overcolor':co_over_OHIO,
		'downcolor':co_down_OHIO,
		'enable':if_OHIO,
	},	
	'map_36':{
		'namesId':'OK',
		'name': 'OKLAHOMA',
		'url':'../apartment/university.html?areaid='+vi_OKLAHOMA,
		'target':'_parent',
		'upcolor':co_up_OKLAHOMA,
		'overcolor':co_over_OKLAHOMA,
		'downcolor':co_down_OKLAHOMA,
		'enable':if_OKLAHOMA,
	},
	'map_37':{
		'namesId':'OR',
		'name': 'OREGON',
		'url':'../apartment/university.html?areaid='+vi_OREGON,
		'target':'_parent',
		'upcolor':co_up_OREGON,
		'overcolor':co_over_OREGON,
		'downcolor':co_down_OREGON,
		'enable':if_OREGON,
	},
	'map_38':{
		'namesId':'PA',
		'name': 'PENNSYLVANIA',
		'url':'../apartment/university.html?areaid='+vi_PENNSYLVANIA,
		'target':'_parent',
		'upcolor':co_up_PENNSYLVANIA,
		'overcolor':co_over_PENNSYLVANIA,
		'downcolor':co_down_PENNSYLVANIA,
		'enable':if_PENNSYLVANIA,
	},	
	'map_39':{
		'namesId':'RI',
		'name': 'RHODE ISLAND',
		'url':'../apartment/university.html?areaid='+vi_RHODE_ISLAND,
		'target':'_parent',
		'upcolor':co_up_RHODE_ISLAND,
		'overcolor':co_over_RHODE_ISLAND,
		'downcolor':co_down_RHODE_ISLAND,
		'enable':if_RHODE_ISLAND,
	},
	'map_40':{
		'namesId':'SC',
		'name': 'SOUTH CAROLINA',
		'url':'../apartment/university.html?areaid='+vi_SOUTH_CAROLINA,
		'target':'_parent',
		'upcolor':co_up_SOUTH_CAROLINA,
		'overcolor':co_over_SOUTH_CAROLINA,
		'downcolor':co_down_SOUTH_CAROLINA,
		'enable':if_SOUTH_CAROLINA,
	},
	'map_41':{
		'namesId':'SD',
		'name': 'SOUTH DAKOTA',
		'url':'../apartment/university.html?areaid='+vi_SOUTH_DAKOTA,
		'target':'_parent',
		'upcolor':co_up_SOUTH_DAKOTA,
		'overcolor':co_over_SOUTH_DAKOTA,
		'downcolor':co_down_SOUTH_DAKOTA,
		'enable':if_SOUTH_DAKOTA,
	},	
	'map_42':{
		'namesId':'TN',
		'name': 'TENNESSEE',
		'url':'../apartment/university.html?areaid='+vi_TENNESSEE,
		'target':'_parent',
		'upcolor':co_up_TENNESSEE,
		'overcolor':co_over_TENNESSEE,
		'downcolor':co_down_TENNESSEE,
		'enable':if_TENNESSEE,
	},
	'map_43':{
		'namesId':'TX',
		'name': 'TEXAS',
		'url':'../apartment/university.html?areaid='+vi_TEXAS,
		'target':'_parent',
		'upcolor':co_up_TEXAS,
		'overcolor':co_over_TEXAS,
		'downcolor':co_down_TEXAS,
		'enable':if_TEXAS,
	},
	'map_44':{
		'namesId':'UT',
		'name': 'UTAH',
		'url':'../apartment/university.html?areaid='+vi_UTAH,
		'target':'_parent',
		'upcolor':co_up_UTAH,
		'overcolor':co_over_UTAH,
		'downcolor':co_down_UTAH,
		'enable':if_UTAH,
	},
	'map_45':{
		'namesId':'VT',
		'name': 'VERMONT',
		'url':'../apartment/university.html?areaid='+vi_VERMONT,
		'target':'_parent',
		'upcolor':co_up_VERMONT,
		'overcolor':co_over_VERMONT,
		'downcolor':co_down_VERMONT,
		'enable':if_VERMONT,
	},	
	'map_46':{
		'namesId':'VA',
		'name': 'VIRGINIA',
		'url':'../apartment/university.html?areaid='+vi_VIRGINIA,
		'target':'_parent',
		'upcolor':co_up_VIRGINIA,
		'overcolor':co_over_VIRGINIA,
		'downcolor':co_down_VIRGINIA,
		'enable':if_VIRGINIA,
	},
	'map_47':{
		'namesId':'WA',
		'name': 'WASHINGTON',
		'url':'../apartment/university.html?areaid='+vi_WASHINGTON,
		'target':'_parent',
		'upcolor':co_up_WASHINGTON,
		'overcolor':co_over_WASHINGTON,
		'downcolor':co_down_WASHINGTON,
		'enable':if_WASHINGTON,
	},
	'map_48':{
		'namesId':'WV',
		'name': 'WEST VIRGINIA',
		'url':'../apartment/university.html?areaid='+vi_WEST_VIRGINIA,
		'target':'_parent',
		'upcolor':co_up_WEST_VIRGINIA,
		'overcolor':co_over_WEST_VIRGINIA,
		'downcolor':co_down_WEST_VIRGINIA,
		'enable':if_WEST_VIRGINIA,
	},	
	'map_49':{
		'namesId':'WI',
		'name': 'WISCONSIN',
		'url':'../apartment/university.html?areaid='+vi_WISCONSIN,
		'target':'_parent',
		'upcolor':co_up_WISCONSIN,
		'overcolor':co_over_WISCONSIN,
		'downcolor':co_down_WISCONSIN,
		'enable':if_WISCONSIN,
	},
	'map_50':{
		'namesId':'WY',
		'name': 'WYOMING',
		'url':'../apartment/university.html?areaid='+vi_WYOMING,
		'target':'_parent',
		'upcolor':co_up_WYOMING,
		'overcolor':co_over_WYOMING,
		'downcolor':co_down_WYOMING,
		'enable':if_WYOMING,
	},
	'map_51':{
		'namesId':'DC',
		'name': 'WASHINGTON DC',
		'url':'../apartment/university.html?areaid='+vi_WASHINGTON_DC,
		'target':'_parent',
		'upcolor':co_up_WASHINGTON_DC,
		'overcolor':co_over_WASHINGTON_DC,
		'downcolor':co_down_WASHINGTON_DC,
		'enable':if_WASHINGTON_DC,
	},
}
